# Post the outcome of a worfklow run into Slack.
name: Slack
on:
  workflow_call:
    inputs:
      message:
        type: string
        description: "The message to post to Slack"
    secrets:
      SLACK_BOT_TOKEN:
        required: true
jobs:
  Slack:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C4K6M7P5E'
          slack-message: "${{ inputs.message }}\n*Conclusion:* ${{ github.event.workflow_run.conclusion }}\n*Repo:* `${{ github.event.repository.full_name }}` (${{ github.event.repository.html_url }})\n*Workflow:* ${{ github.event.workflow.name }} (${{ github.event.workflow.html_url }})\n*Branch:* `${{ github.event.workflow_run.head_branch }}`\n*Commit:* `${{ github.event.workflow_run.head_commit.id }}`\n*Run:* ${{ github.event.workflow_run.html_url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
